### ISSUE TITLE
store days of the week in group model/table

### ISSUE THREAD

**Issue by Lipemenezes** [Lipemenezes/inclass-server#1]
In our system's point of view, Groups have Lectures in some days of the week and we need to store this information.

Ideas:

1 - Many to Many table between Group and DaysOfTheWeek.
2 - Create one boolean field for each day of the week in Group.

**Comment by amadeu01** [comment]
I guess you could create a table called `Calendar` which store data about `Events` which might be `Classes`, `Party`, `Social Events`...

Then, you have to that event a user, or a group of users attached to that event. And, that event could be periodic until a certain date.

So, it could be something like:


Calendar -> Events -> Group
                                |
                                | -> Periodical

**Comment by amadeu01** [comment]
1. Change the databse to postgres!

**Comment by amadeu01** [comment]
You could use JSON on the SQL to store information about which lecture and when the user/group of users will have an appointment.
